[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1
hook_post_source = '''
let g:deoplete#omni_patterns = {}
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
on_ft = 'snipppet'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'


[[plugins]]
repo = 'carlitux/deoplete-ternjs'
hook_add = '''
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]
'''
on_i = 1
